# Generated by Django 3.2 on 2021-04-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
