# Generated by Django 3.2 on 2021-04-22 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='auth_user',
            field=models.OneToOneField(db_column='auth_user', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user', verbose_name='Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='22shubh22@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mob_number',
            field=models.CharField(default='7780984023', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
