# Generated by Django 3.2 on 2021-04-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210422_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='auth_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='shyam', max_length=200),
            preserve_default=False,
        ),
    ]
