# Generated by Django 3.2 on 2021-04-24 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connected_users',
            field=models.ManyToManyField(blank=True, related_name='connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
